### ISSUE TITLE
Investigate and fix the slowness through #p1-gp-bsigroup-website

### ISSUE THREAD

**Issue by susilparida** [k8-proxy/gp-bsigroup-website#13]
Investigate and fix the slowness through #p1-gp-bsigroup-website  proxy search result for "Food Training" takes 2.4 minute as shown in the screenshot below, Same thing for direct site takes 7.7 sec.  Please investigate, whether our installation / which specific service is bottleneck. Increase the worked node capacity. It can not be ICAP rebuild is the only culprit.

**Comment by hongson1981** [comment]
Investigation solution :
On Squid proxy
  1. Create ACL list to filter content-type : pdf, document, image ..
  2. By default : Do not allow forward data to ICAP server
  3. Only allow forward data which have content-type on ACL list of step 1 to ICAP server
