### ISSUE TITLE
Dependent drop down does not populate 

### ISSUE THREAD

**Issue by susilupwork** [k8-proxy/gp-bsigroup-website#14]
Dynamic content, which gets loaded via ajax call does not get populated 

Go to https://www.bsigroup.com.glasswall-icap.com/en-GB/industries-and-sectors/food-and-drink/food-training-courses/ 

-  Go to "More courses" area 
-  Select any course from drop down e.g  "Asset Mgmt" 
-  Tyr to select Location drop down- The drop down is blank.

**Comment by hongson1981** [comment]
![image](https://user-images.githubusercontent.com/29745336/98314632-feb47a80-2008-11eb-9e6a-60b79163c8ef.png)
The list load very slow, maybe ICAP process
In my PC, it take 2 minutes to load location list
