### ISSUE TITLE
Deploy application and setup the proxy - SOW V0.2

### ISSUE THREAD

**Issue by susilparida** [k8-proxy/gp-bsigroup-website#3]
Target URL for Proxy are :
https://www.bsigroup.com/en-GB (Primary URL)
https://page.bsigroup.com/ (CDN URL)

It will proxy of SOW v0.2 with following features

Follow implemented path at https://github.com/k8-proxy/gp-emma-dataport-website for SOW v0.2

**Comment by hongson1981** [comment]
This task completed and ready for review,
please check 2 sites 
https://www.bsigroup.com.glasswall-icap.com/en-GB (Primary URL)
https://page.bsigroup.com.glasswall-icap.com (CDN URL)
